[versions]
compose = "1.2.0-rc01"
accompanist = "0.24.11-rc"

[libraries]
activity = "androidx.activity:activity-compose:1.6.0-alpha05"
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }

material3-core = "androidx.compose.material3:material3:1.0.0-alpha13"
material3-adapter = "com.google.android.material:compose-theme-adapter-3:1.0.11"
material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }

accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }